resp_codes = {
    '1': 'Wallet address already exists!',
    '2': 'Provider name already exists!',
    '3': 'Name or wallet address already exist',
    '4': 'Vicinity OID not found in DB',
    '5': 'Provider ID not found in DB',
    '6': 'Wallet ID not found in DB',
    '7': 'URI must have /providers/{id} format',
    '8': 'Infrastructure not found in DB',
    '9': 'Infrastructure or provider not found in DB',
    '10': 'Wallet has no valid address/privateKey',
    '11': 'Provider already has one pricing contract',
    '12': 'Providers does not have enough balance to deploy a pricing contract',
    '13': 'Provider does not have a pricing contract',
    '14': 'Contract address already exists',
    '15': 'Infrastructure vicinity_oid already exists!',
    '16': 'End user not found in DB',
    '17': 'Pricing contract not found in db',
    '18': 'Multisig not found in DB',
    '19': 'Trasaction mined but failed',
    '20': 'Oid not found in agent configuration',
    '22' : 'OCP could not create charger',
    '23' : 'Invalid set of coordinates',
    '24' : 'Coordinates have no address nor route'

}